import {AnalysisError,MAX_GAP,gpsRoute,meters,type Point,type Route} from './core.ts';
type Pair=[number,number];
type Profile={segments:Pair[][];average_s_per_km:number|null;fastest_point:{distance_m:number;pace_s_per_km:number}|null;slowest_s_per_km:number|null;gps_freeze_s:number};
const second=(a:Point,b:Point)=>(b.time-a.time)/1000;
function lower(a:number[],x:number):number{let lo=0,hi=a.length;while(lo<hi){const m=(lo+hi)>>>1;if(a[m]<x)lo=m+1;else hi=m}return lo}
function coordinate(r:Route,target:number){const p=r.points,d=r.distances;if(target<0||target>d.at(-1)!+1e-5)throw new AnalysisError('La distance choisie dépasse la longueur d’une trace.');target=Math.min(target,d.at(-1)!);const i=Math.min(lower(d,target-1e-5),p.length-1);const a=p[i];if(i===0||Math.abs(d[i]-target)<1e-5)return {index:i,time:a.time,lat:a.lat!,lon:a.lon!,ele:a.ele};const prev=p[i-1];if(prev.segment!==a.segment)throw new AnalysisError('La coupe tombe sur une interruption entre segments GPX.');const f=(target-d[i-1])/(d[i]-d[i-1]);return {index:i,time:prev.time+(a.time-prev.time)*f,lat:prev.lat!+(a.lat!-prev.lat!)*f,lon:prev.lon!+(a.lon!-prev.lon!)*f,ele:prev.ele!==null&&a.ele!==null?prev.ele+(a.ele-prev.ele)*f:null}}
function thinRuns(runs:Pair[][],isolated:Pair[]=[],limit=5000):[Pair[][],Pair[]]{const total=runs.reduce((n,r)=>n+r.length,isolated.length);if(total<=limit)return [runs,isolated];const stride=Math.ceil(total/Math.floor(limit/2));const reduced=runs.map(run=>{if(run.length<=2)return run;const keep=new Set([0,run.length-1]);for(let start=1;start<run.length-1;start+=stride){let lo=start,hi=start;for(let k=start;k<Math.min(start+stride,run.length-1);k++){if(run[k][1]<run[lo][1])lo=k;if(run[k][1]>run[hi][1])hi=k}keep.add(lo);keep.add(hi)}return [...keep].sort((a,b)=>a-b).map(i=>run[i])});if(isolated.length){let min=0,max=0;for(let i=1;i<isolated.length;i++){if(isolated[i][1]<isolated[min][1])min=i;if(isolated[i][1]>isolated[max][1])max=i}const keep=new Set([0,isolated.length-1,min,max]);for(let i=0;i<isolated.length;i+=stride)keep.add(i);isolated=[...keep].sort((a,b)=>a-b).map(i=>isolated[i])}return [reduced,isolated]}
export function preview(route:Route){const r=gpsRoute(route),p=r.points,d=r.distances;if(d.at(-1)!<10)throw new AnalysisError('Cette trace est trop courte pour sélectionner un segment de 10 m.');let groups:number[][][]=[],run:number[][]=[],previous:Point|null=null;for(let i=0;i<p.length;i++){const point=p[i];if(run.length&&previous&&(point.segment!==previous.segment||second(previous,point)>MAX_GAP)){groups.push(run);run=[]}run.push([d[i],point.lat!,point.lon!]);previous=point}if(run.length)groups.push(run);const count=groups.reduce((n,r)=>n+r.length,0),stride=Math.max(1,Math.floor((count-1)/Math.max(1,2400-groups.length))+1);groups=groups.map(g=>g.length<3?g:[g[0],...g.slice(1,-1).filter((_,i)=>i%stride===0),g.at(-1)!]);return {distance_m:d.at(-1)!,geometry:groups,points:p.length}}
function paceProfile(r:Route,start:number,end:number):Profile{const p=r.points,d=r.distances,runs:Pair[][]=[];let run:Pair[]=[],movingSeconds=0,movingMeters=0,freezeSeconds=0;const flush=()=>{if(run.length>1)runs.push(run);run=[]};let i=0;while(i<p.length-1){const a=p[i],b=p[i+1],d0=d[i],d1=d[i+1],dt=second(a,b);if(d0>=end)break;
    if(d1<=d0&&a.segment===b.segment&&dt>0&&dt<=MAX_GAP){let j=i;while(j<p.length-1&&d[j+1]<=d[j]&&p[j].segment===p[j+1].segment&&second(p[j],p[j+1])>0&&second(p[j],p[j+1])<=MAX_GAP)j++;const frozen=(p[j].time-p[i].time)/1000;const next=j<p.length-1&&p[j].segment===p[j+1].segment&&d[j+1]>d[j]&&second(p[j],p[j+1])>0&&second(p[j],p[j+1])<=MAX_GAP;const supported=p.slice(i,j+1).every(q=>q.cadence!==null&&q.cadence>0&&q.power!==null&&q.power>0);if(run.length&&Math.abs(run.at(-1)![0]-d0)<1e-5&&next&&frozen>0&&frozen<=15&&supported&&start<=d0&&d0<end){movingSeconds+=frozen;freezeSeconds+=frozen;i=j;continue}flush();i=j;continue}
    if(a.segment!==b.segment||dt<=0||dt>MAX_GAP||d1<=d0||d1<=start){flush();i++;continue}
    const lo=Math.max(d0,start),hi=Math.min(d1,end);if(hi<=lo){i++;continue}const t0=(a.time-p[0].time)/1000,lt=t0+dt*(lo-d0)/(d1-d0),ht=t0+dt*(hi-d0)/(d1-d0);movingSeconds+=ht-lt;movingMeters+=hi-lo;if(run.length&&Math.abs(run.at(-1)![0]-lo)>1e-5)flush();if(!run.length)run.push([lo,lt]);run.push([hi,ht]);i++}flush();
  const timeAt=(run:Pair[],positions:number[],distance:number)=>{const j=Math.min(Math.max(1,lower(positions,distance)),run.length-1),a=run[j-1],b=run[j];return a[1]+(b[1]-a[1])*(distance-a[0])/(b[0]-a[0])};
  const curves:Pair[][]=[];for(const run of runs){const rs=run[0][0],re=run.at(-1)![0],required=Math.abs(rs-start)<1e-5&&Math.abs(re-end)<1e-5?50:100;if(re-rs<required-1e-5)continue;const positions=run.map(x=>x[0]),curve:Pair[]=[];for(const [distance] of run){let lo:number,hi:number;if(re-rs<100-1e-5){lo=rs;hi=re}else{lo=Math.min(Math.max(distance-50,rs),re-100);hi=lo+100}const pace=1000*(timeAt(run,positions,hi)-timeAt(run,positions,lo))/(hi-lo);if(pace>0&&Number.isFinite(pace))curve.push([distance,pace])}if(curve.length>=2)curves.push(curve)}
  let fastest=Infinity,slowest=-Infinity,peak:Pair|null=null;
  for(const curve of curves)for(const sample of curve){if(sample[1]<fastest-1e-5||(!peak&&sample[1]<=fastest+1e-5)){fastest=sample[1];peak=sample}else if(sample[1]<=fastest+1e-5&&peak&&sample[0]<peak[0])peak=sample;slowest=Math.max(slowest,sample[1])}
  const [reduced]=thinRuns(curves);if(peak){const original=curves.find(run=>run.includes(peak));const index=curves.indexOf(original!);if(index>=0&&!reduced[index].includes(peak)){reduced[index].push(peak);reduced[index].sort((a,b)=>a[0]-b[0])}}
  return {segments:reduced,average_s_per_km:peak&&movingMeters?1000*movingSeconds/movingMeters:null,fastest_point:peak?{distance_m:peak[0],pace_s_per_km:peak[1]}:null,slowest_s_per_km:peak?slowest:null,gps_freeze_s:freezeSeconds};
}
export function rangeStats(route:Route,startM:number,endM:number,factor:number){const r=gpsRoute(route),p=r.points,d=r.distances;if(!Number.isFinite(startM)||!Number.isFinite(endM)||!(0<=startM&&startM<endM&&endM<=d.at(-1)!+1e-5&&endM-startM>=10-1e-5))throw new AnalysisError('Bornes invalides : choisissez au moins 10 m dans chaque trace.');endM=Math.min(endM,d.at(-1)!);const start=coordinate(r,startM);let finish=coordinate(r,endM);if(Math.abs(endM-d.at(-1)!)<1e-5){const last=p.at(-1)!;finish={index:p.length-1,time:last.time,lat:last.lat!,lon:last.lon!,ele:last.ele}}const duration=(finish.time-start.time)/1000;if(duration<=0)throw new AnalysisError('Les timestamps du segment ne permettent pas un chrono positif.');
  const totals={hr:0,power:0,cadence:0},coverage={...totals},maxima:{hr:number|null;power:number|null;cadence:number|null}={hr:null,power:null,cadence:null};type Metric=keyof typeof totals;let gain=0,loss=0,elevationCovered=0;const hrRuns:Pair[][]=[],hrStarts=new Set<number>();let previousEnd:number|null=null;
  for(let i=Math.max(0,lower(d,startM)-1);i<p.length-1;i++){const a=p[i],b=p[i+1],d0=d[i],d1=d[i+1];if(d0>endM||(d0===endM&&endM<d.at(-1)!-1e-5))break;if(a.segment!==b.segment){previousEnd=null;continue}const dt=second(a,b);if(dt<=0||dt>MAX_GAP){previousEnd=null;continue}const span=d1-d0;let lo:number,hi:number,fraction:number;if(span>0){lo=Math.max(startM,d0);hi=Math.min(endM,d1);if(hi<=lo)continue;fraction=(hi-lo)/span}else{if(!(startM<=d0&&d0<=endM)||b.time>finish.time)continue;lo=hi=d0;fraction=1}
    const weighted=dt*fraction;if(a.ele!==null&&b.ele!==null){const delta=(b.ele-a.ele)*fraction;gain+=Math.max(0,delta);loss+=Math.max(0,-delta);elevationCovered+=weighted}const values={hr:a.hr,power:a.power,cadence:a.cadence!==null&&a.cadence>0?a.cadence*factor:null};if(a.hr!==null){if(previousEnd!==i||!hrRuns.length)hrRuns.push([]);const run=hrRuns.at(-1)!;if(!run.length||run.at(-1)![0]!==lo||run.at(-1)![1]!==a.hr)run.push([lo,a.hr]);run.push([hi,a.hr]);hrStarts.add(i);previousEnd=i+1}else previousEnd=null;
    for(const k of ['hr','power','cadence'] as Metric[]){const v=values[k];if(v!==null){totals[k]+=v*weighted;coverage[k]+=weighted;maxima[k]=Math.max(maxima[k]??v,v)}}}
  const last=finish.index;if(Math.abs(d[last]-endM)<1e-5){const q=p[last],values={hr:q.hr,power:q.power,cadence:q.cadence!==null&&q.cadence>0?q.cadence*factor:null};for(const k of ['hr','power','cadence'] as Metric[]){const v=values[k];if(v!==null)maxima[k]=Math.max(maxima[k]??v,v)}}
  let maxHR:number|null=null,minHR:number|null=null,peak:Pair|null=null;
  const consider=(sample:Pair)=>{const v=sample[1];minHR=minHR===null?v:Math.min(minHR,v);if(maxHR===null||v>maxHR||(v===maxHR&&peak&&sample[0]<peak[0])){maxHR=v;peak=sample}};
  const isolated:Pair[]=[];
  for(let i=Math.max(0,lower(d,startM)-1);i<p.length&&d[i]<=endM+1e-5;i++){
    const q=p[i];if(q.hr===null||q.time<start.time||q.time>finish.time||d[i]<startM-1e-5)continue;
    const sample:Pair=[Math.max(startM,Math.min(endM,d[i])),q.hr];consider(sample);if(!hrStarts.has(i))isolated.push(sample);
  }
  for(const run of hrRuns)for(const sample of run)consider(sample);
  maxima.hr=maxHR;const [hrSegments,hrIsolated]=thinRuns(hrRuns,isolated),pace=paceProfile(r,startM,endM);
  const hrMinimum=minHR as number|null;
  const metrics=Object.fromEntries((['hr','power','cadence'] as Metric[]).map(k=>[k,{average:coverage[k]?totals[k]/coverage[k]:null,maximum:maxima[k],covered_s:coverage[k]}])) as Record<Metric,{average:number|null;maximum:number|null;covered_s:number}>;
  return {start_m:startM,end_m:endM,distance_km:(endM-startM)/1000,duration_s:duration,pace_s_per_km:duration/((endM-startM)/1000),elevation_gain_m:elevationCovered?gain:null,elevation_loss_m:elevationCovered?loss:null,metrics,hr_series:{segments:hrSegments,isolated:hrIsolated,minimum_bpm:hrMinimum,maximum_point:peak?{distance_m:peak[0],bpm:peak[1]}:null},pace_series:pace,start:{lat:start.lat,lon:start.lon},finish:{lat:finish.lat,lon:finish.lon}};
}
export function compareRanges(first:Route,second:Route,firstStart:number,firstEnd:number,secondStart:number,secondEnd:number,cadenceFirst:'double'|'direct'='double',cadenceSecond:'double'|'direct'='double'){
  const a=rangeStats(first,firstStart,firstEnd,cadenceFirst==='double'?2:1),b=rangeStats(second,secondStart,secondEnd,cadenceSecond==='double'?2:1);
  const minima=[a.hr_series.minimum_bpm,b.hr_series.minimum_bpm].filter((v):v is number=>v!==null),slowest=[a.pace_series.slowest_s_per_km,b.pace_series.slowest_s_per_km].filter((v):v is number=>v!==null);
  return {reference:a,challenger:b,delta_s:b.duration_s-a.duration_s,hr_common_min_bpm:minima.length?Math.min(...minima):null,pace_common_slowest_s_per_km:slowest.length?Math.max(...slowest):null,distance_delta_m:(b.distance_km-a.distance_km)*1000,start_separation_m:meters([a.start.lat,a.start.lon],[b.start.lat,b.start.lon]),finish_separation_m:meters([a.finish.lat,a.finish.lon],[b.finish.lat,b.finish.lon]),warnings:['Sélection libre : un écart de chrono ne démontre pas une vitesse supérieure si les parcours diffèrent.','Cadence estimée selon la conversion choisie par fichier ; zéros exclus.','D+/D− issus des variations d’altitude brutes, sensibles au bruit GPS.']};
}
